"""empty message

Revision ID: 6ee2e95c4cc2
Revises:
Create Date: 2017-11-22 08:55:16.179331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee2e95c4cc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'experiment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code_version', sa.String(length=50), nullable=False),
        sa.Column('form_data', sa.PickleType(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('submitted', 'queued', 'running', 'finished', 'error', name='experimentstatus'),
            nullable=False),
        sa.Column('log', sa.Text(), server_default='', nullable=True),
        sa.Column('results', sa.Text(), nullable=True),
        sa.Column('submitted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('completed', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment')
    # ### end Alembic commands ###
