"""empty message

Revision ID: b75e873a8995
Revises: 732ceed631eb
Create Date: 2018-01-29 14:19:06.418437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75e873a8995'
down_revision = '732ceed631eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('name', sa.String(length=50),
                  server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment', 'name')
    # ### end Alembic commands ###
